### PR TITLE
fix:enuse mainFileAbsolutePath is an absolutePath.

### PR DESCRIPTION
**Pull request by jinphic**
entryFilePath was assigned by options.entry.
options.entry may be a relative path, pkgJson.main is also a relative path to the root directory.
with path.join(entryFilePath, pkgJson.main), result is a relative path.

### CODE REVIEW

**Comment by JackLian** [comment]
please change the target branch to develop

**Comment by jinphic** [comment]
> please change the target branch to develop

done.

**Comment by liujuping** [comment]
with path.resolve(entryFilePath, pkgJson.main), result is not necessarily a absolute path.

**Comment by jinphic** [comment]
> with path.resolve(entryFilePath, pkgJson.main), result is not necessarily a absolute path.

The path.resolve() method resolves a sequence of paths or path segments into an absolute path。
mainFileAbsolutePath is not necessarily a absolute path ？

**Comment by liujuping** [comment]
There are many situations here, and I am not sure what the side effects of this change will be.

// 1.same results
console.log(path.resolve('/img/books', 'net'));   // returns '/img/books/net'
console.log(path.join('/img/books', 'net'));      // returns '/img/books/net'

// 2.different results
console.log(path.resolve('/img/books', '/net'))   // returns '/net'
console.log(path.join('/img/books', '/net'))      // returns '/img/books/net'

// 3.absolute path
console.log(path.resolve('img/books', './net'))  // returns '/workspace/demo/img/books/net'

**Comment by jinphic** [comment]
> pkgJson.main is also a relative path to the root directory



> There are many situations here, and I am not sure what the side effects of this change will be.
> 
> // 1.same results console.log(path.resolve('/img/books', 'net')); // returns '/img/books/net' console.log(path.join('/img/books', 'net')); // returns '/img/books/net'
> 
> // 2.different results console.log(path.resolve('/img/books', '/net')) // returns '/net' console.log(path.join('/img/books', '/net')) // returns '/img/books/net'
> 
> // 3.absolute path console.log(path.resolve('img/books', './net')) // returns '/workspace/demo/img/books/net'

For Situation 1 and Situation 3, the changes are correct.
Is Situation2 exist ? pkgJson.main , a relative path,  starts with '/net',  instead of './net' or 'net'

**Comment by liujuping** [comment]
> > pkgJson.main is also a relative path to the root directory
> 
> > There are many situations here, and I am not sure what the side effects of this change will be.
> > // 1.same results console.log(path.resolve('/img/books', 'net')); // returns '/img/books/net' console.log(path.join('/img/books', 'net')); // returns '/img/books/net'
> > // 2.different results console.log(path.resolve('/img/books', '/net')) // returns '/net' console.log(path.join('/img/books', '/net')) // returns '/img/books/net'
> > // 3.absolute path console.log(path.resolve('img/books', './net')) // returns '/workspace/demo/img/books/net'
> 
> For Situation 1 and Situation 3, the changes are correct. Is Situation2 exist ? pkgJson.main , a relative path, starts with '/net', instead of './net' or 'net'

Is Situation3 exist ? In accesser equal 'local', internalOptions.entry is a absolutePath. 

image

In accesser equal 'online', internalOptions.entry is a absolutePath. 

image

The result of path.resolve is:
```
console.log(path.resolve('/img/books', 'net'))   // returns '/img/books/net'
console.log(path.resolve('/img/books', './net'))   // returns '/img/books/net'
```

**Comment by jinphic** [comment]
> > > pkgJson.main is also a relative path to the root directory
> > 
> > 
> > > There are many situations here, and I am not sure what the side effects of this change will be.
> > > // 1.same results console.log(path.resolve('/img/books', 'net')); // returns '/img/books/net' console.log(path.join('/img/books', 'net')); // returns '/img/books/net'
> > > // 2.different results console.log(path.resolve('/img/books', '/net')) // returns '/net' console.log(path.join('/img/books', '/net')) // returns '/img/books/net'
> > > // 3.absolute path console.log(path.resolve('img/books', './net')) // returns '/workspace/demo/img/books/net'
> > 
> > 
> > For Situation 1 and Situation 3, the changes are correct. Is Situation2 exist ? pkgJson.main , a relative path, starts with '/net', instead of './net' or 'net'
> 
> Is Situation3 exist ? In accesser equal 'local', internalOptions.entry is a absolutePath.
> 
> image
> 
> In accesser equal 'online', internalOptions.entry is a absolutePath.
> 
> image
> 
> The result of path.resolve is:
> 
> ```
> console.log(path.resolve('/img/books', 'net'))   // returns '/img/books/net'
> console.log(path.resolve('/img/books', './net'))   // returns '/img/books/net'
> ```

back to the code changes` model.mainFileAbsolutePath = model.mainFileAbsolutePath || join(entryFilePath, pkgJson.main);`.  When model.mainFileAbsolutePath is NIL, the first parameters is entryFilePath  and entryFilePath is just assign by options.entry.
image

just for code execution， It must be a potential bug

**Comment by liujuping** [comment]
> > > > pkgJson.main is also a relative path to the root directory
> > > 
> > > 
> > > > There are many situations here, and I am not sure what the side effects of this change will be.
> > > > // 1.same results console.log(path.resolve('/img/books', 'net')); // returns '/img/books/net' console.log(path.join('/img/books', 'net')); // returns '/img/books/net'
> > > > // 2.different results console.log(path.resolve('/img/books', '/net')) // returns '/net' console.log(path.join('/img/books', '/net')) // returns '/img/books/net'
> > > > // 3.absolute path console.log(path.resolve('img/books', './net')) // returns '/workspace/demo/img/books/net'
> > > 
> > > 
> > > For Situation 1 and Situation 3, the changes are correct. Is Situation2 exist ? pkgJson.main , a relative path, starts with '/net', instead of './net' or 'net'
> > 
> > 
> > Is Situation3 exist ? In accesser equal 'local', internalOptions.entry is a absolutePath.
> > image
> > In accesser equal 'online', internalOptions.entry is a absolutePath.
> > image
> > The result of path.resolve is:
> > ```
> > console.log(path.resolve('/img/books', 'net'))   // returns '/img/books/net'
> > console.log(path.resolve('/img/books', './net'))   // returns '/img/books/net'
> > ```
> 
> back to the code changes` model.mainFileAbsolutePath = model.mainFileAbsolutePath || join(entryFilePath, pkgJson.main);`. When model.mainFileAbsolutePath is NIL, the first parameters is entryFilePath and entryFilePath is just assign by options.entry. image
> 
> just for code execution， It must be a potential bug

The parameter options in the scan method comes from modules/material-parser/src/index.ts

in modules/material-parser/src/index.ts
Options.entry provided to the scan method is not overwritten only if options.root does not exist.

Do other situations also need to be dealt with?

**Comment by liujuping** [comment]
I have closed this PR first. I hope that in the future, it will be supported through options to control whether to use absolutePath, and all branches will be able to support absolutePath.

**Pull request closed without merging**
