### PR TITLE
fix: change typescript type export to export type

### PR DESCRIPTION
**Pull request by meizilove258**
vite + esbuild will error

### CODE REVIEW

**Comment by meizilove258** [comment]
@LeoYuan @JackLian @liujuping  这次能过了么

**Comment by liujuping** [comment]
可以 1.0.14-beta.0 验证一下

**Comment by meizilove258** [comment]
ok

**Comment by liujuping** [comment]
close https://github.com/alibaba/lowcode-engine/issues/890

**Pull request merged**
